import { Inter } from "next/font/google";
import "./globals.css";
import DGB_header from "./components/SiteHeader/SiteHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DGB_header />
        <video loop autoPlay muted className="main_video">
          <source src="for_website_filter.mp4" type="video/mp4" />
          Ваш браузер не підтримує тег відео.
        </video>
        {children}
      </body>
    </html>
  );
}
